apiVersion: v1
kind: Service
metadata:
  labels:
    name: backend-service
  name: backend-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8081
    targetPort: 8080
    protocol: TCP
  selector:
    name: backend-service
    role: config
