apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: backend-node
  name: backend-node
spec:
  replicas: 3
  template:
    metadata:
      name: backend-node
      labels:
        labels:
        app: $APP_NAME
        role: frontend
        env: config    
    spec:
      containers:
      - image: gcr.io/<PROJECT ID>/backend:v1.0
        name: backend-node
        ports:
        - name: PORT
          value: "8081"

