apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: frontend-node
spec:
   selector:
    matchLabels:
      app: $APP_NAME
      role: frontend
      env: config
  replicas: 3
  template:
    metadata:
      name: frontend-node
      labels:
        app: $APP_NAME
        role: frontend
        env: config
    spec:
      containers:
      - name: frontend
        image: gcr.io/<PROJECT ID>/frontend:v1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        ports:
        - name: PORT
          value: "8080"
